config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :hello
  root 'hello#index'

  Rails.application.routes.draw do
    get 'maps/index'
    resources :maps, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  mount_uploader :image, ImageUploader
  
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])

    end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def 
    index
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
      like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
    end

  end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
    search = params[:search]
    @tweets = @tweets.joins(:user).where("body LIKE ?", "%#{search}%") if search.present?
    @tweets = @tweets.page(params[:page]).per(3)
    end
    
  def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id
        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
      end

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end
      private
      def tweet_params
        params.require(:tweet).permit(:body,:place,:image,:lat,:lng)
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
      @tweets = Tweet.all
    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= stylesheet_link_tag 'top', :media => "all" %>

<header1>
  <div class="container">
    <nav>
      <div class="logo">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
           viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve">
          <style type="text/css">
            .st0{fill:#FFFFFF;}
            .st1{fill:#B93D30;}
          </style>
          <circle class="st0" cx="25" cy="25" r="25"/>
          <g>
            <polygon class="st1" points="34.1,25 27.7,13.9 21.3,25 19.2,28.7 16.5,24 13,30 9.5,36.1 14.9,36.1 16.5,36.1 23.5,36.1 
                           27.7,36.1 40.5,36.1  "/>
          </g>
        </svg>
      </div>
      <div class="subscribe">
        <a href="#">Subscribe</a>
      </div>
    </nav>
    <blockquote>私たちが愛すべき夜、nuit nuit は<div class="sns">"夜限定のsns"です。
    </div>
    <span>&mdash; Plannner :Keiju Sakagami
    </span>
    </blockquote>
    <div class="date">
      <i class="fa fa-calendar" aria-hidden="true"></i> 
      Aplil 20, 2024
    </div>
  </div>
</header1>

<section>
  <div class="scroll">
    <i class="fa fa-long-arrow-down" aria-hidden="true"></i>
  </div>
  <div class="container">
    <h1>I like the night. Without the dark,we'd never see the stars.</h1>
    <div class="byline">
      <div class="avatar"></div>
      by <span>Stephenie Meyer</span>
    </div>
    <p class="hide"><span class="drop">夜</span> アメリカの作家であるステファニー・メイヤーは前述のような言葉を残しました。直訳すると「私は夜が好きだ。夜がなければ私たちは星を見ることができなかったであろう。」<br>
    "nuit"これはフランス語で夜を指す言葉です。夜といってもみんなが寝静まった真夜中です。 </p>

    <p class="hide"> それぞれがそれぞれの景色を見ている。地球に存在する人類は今や80億人を突破しようとしている。自分の見ている景色は自分にしか見えない。<br>nuit nuitはあなたが見ている景色をほかの人と共有してほしい。それぞれの夜を楽しんでつながってほしい、そんな思いから作られたアプリです。</p>
  </div>
</section>

<section class="quote desert">
  <blockquote>Do you like the nuit?</blockquote>
</section>

<section>
  <div class="container">
    <p class="hide">あなたは夜が好きですか？そうと答える人もいれば、違うと答える人もいるでしょう。<br>不安を助長することもあれば、意味もなく沈んだり、怖くなったり、ときには人間を突き動かすことも、、</p>

    <p class="hide">製作者自身も夜に関しては好きな面と嫌いな面があります。夜景、星、普段であればスルーする近所の居酒屋の看板の明かり、、普段では気づかないことがいっぱいある夜。みんなそれぞれが普段とは違った景色を楽しみます。これは、人間に与えられた一つの楽しみ。みんなこの点において夜は好きなのではないでしょうか。。</p>
    
    <!-- <blockquote class="hide">
      Sometimes horses cough and fart at the same time, so stay out of the range of its butt muscle because a horses butt muscle is thick. <span>&mdash; Gary Busey</span>
    </blockquote> -->

    <p class="hide"> ただし、夜には拭えない不安が残ります。日中会えていた友達に会えない孤独感、だれもが感じたことあると思います。実際、このアプリを制作した背景の課題としてその不安の解消があげられます。従来のsnsとは違い、夜限定のsnsであることがあげられます。</p>
  </div>
</section>


<section class="quote second">
  <blockquote>Share your nuit with everyone!!</blockquote>
</section>

<section>
  <div class="container">
    <p class="hide">ここまで来たらあなたがすることは一つ、あなたの見ている景色をみんなに投稿してシェアしましょう！<br>nuit nuitはあなたが訪れた場所、みんなが訪れた場所も投稿時に見れるようになっています。今度行ってみたいな、ここみんなに教えちゃお、などの投稿でいっぱいにしましょう！！！！</p>
    
    <p><strong>Bonne nuit!</strong></p>
    
  </div>
</section>

<section class="comments">
  <div class="container">
    <input type="checkbox" id="toggle" />
    <label class="toggle" for="toggle">
      Planner Comments <i class="indicator"></i>
    </label>
    <div class="wrapper">
      
      <!-- COMMENT -->
      <div class="comment">
        <div class="user">
          <div class="pic"></div>
          <div class="date">04/20/2024</div>
        </div>
        
        <div class="nyaa">
          <div class="author">Keiju Sakagami</div>
          <p>nuit nuitを利用していただいてありがとうございます。開発者の坂上桂寿と申します。
            このアプリは私が夜に一人の時間が多く、寂しくなってしまうということを課題に作成したアプリです。皆さんもたくさん投稿して、今何をしているかをみんなにシェアしちゃいましょう！
            みんながあなたの投稿を待っています！！
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/3abf0b0ef2.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><a href="#"><%= image_tag 'event5.jpg', size: '150x84' %></a></h1>
      <ul>
        <li><%= link_to "ログイン", tweets_path,  class:"btn-vertical-border" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn-vertical-border" %><li>
        <li><%= link_to "新規登録", new_user_registration_path, class:"btn-vertical-border" %></li>
        <li><%= link_to '新規投稿', new_tweet_path, class:"btn-vertical-border" %><li>
        <li><%= link_to "投稿一覧", tweets_path, class:"btn-vertical-border" %><li>
        </ul>
    </header>
    <main>
      <%= yield %>
    </main>
 <footer>
<div class="copyright">
	<p>© 2024 - Organisation</p>
</div>
<div class="sns">
	<a href="#" class="contact">Contact</a>
	<a href="#" class="fb"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></a>
	<a href="#" class="tw"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></a>
	<a href="#" class="insta"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></a>
</div>
</footer>

  </body>
</html>

app/views/tweets/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>
<header4>
  <div class="container">
    <blockquote>Repost
    <span>&mdash; nuit nuit
    </span>
    </blockquote>
  </div>
</header4>
<div class="background_test">

<div class="whole">
<%= form_for @tweet do |f| %>
<div class="content">
  <div class="b1">
    <%= f.label :画像を追加 %>
    <%= f.file_field :image %>
  </div>

  <div class="b2">
    <%= f.label :キャプションを追加  %>
    <%= f.text_area :body, :size => "30x1" %>
  </div>

<div class="b3">
    <%#%= f.label :場所を追加  %>
    <%#%= f.text_field :place, :size => 30 %>
  </div>

<div class="b4">
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
  </div>
  <%= f.submit "投稿する",class:"btn-flat-vertical-border" %>
<% end %>

<div class="mapmap">



<input id="address" type="textbox" value="">
<input type="button" value="検索" onclick="codeAddress()">
<div id='map'></div>

<style>
#map {
  height: 500px;
  width: 500px;
}
</style>

<script>

let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}


let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        
        
        if (aft == true){
            marker.setMap(null);
        }

        
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	
        });

        
        aft = true

        
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        
        google.maps.event.addListener( marker, 'dragend', function(ev){
            
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkbtX1H41LbFUCsV1v1ROwvGFqE6xWL98&callback=initMap" async defer></script>

</div>
</div>
</div>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<header2>
  <div class="container">
    <blockquote>List of all messages
    <span>&mdash; nuit nuit
    </span>
    </blockquote>
  </div>
</header2>
<div class="b10">
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
 <div class="nice wrap">
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
   </div>
<% end %>
<div class="re">
<%= page_entries_info @tweets %>
<%= paginate @tweets %>
</div>
<div class="tweets-container">
  <% @tweets.each do |t| %>
  <p><%= image_tag t.user.image_url, size: "100x100", class: "gazoupro" if t.user.image? %></p>
    <div class="tweet">
      <%= t.user.name %>
      <br>
      <div class="b12">
      <%= t.body %>
      </div>
      <%= t.place %><% if user_signed_in? %>

      <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id), class:"btn-stitch" %>
<% end %>
<div class="b11">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <br>
      <%= link_to "詳細へ", tweet_path(t.id), class:"btn-sticky" %>
            <% if user_signed_in? && current_user.id == t.user_id %>
            <%= link_to "編集する", edit_tweet_path(t.id), class:"btn-sticky" %>
            <%= link_to "削除する", tweet_path(t.id), method: :delete , class:"btn-sticky" %>
          <% end %>
    </div>
    </div>
  <% end %>
</div>
</div>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<header3>
  <div class="container">
    <blockquote>New post
    <span>&mdash; nuit nuit
    </span>
    </blockquote>
  </div>
</header3>
<div class="background_test">

<div class="whole">
<%= form_for @tweet do |f| %>
<div class="content">
  <div class="b1">
    <%= f.label :画像を追加 %>
    <%= f.file_field :image %>
  </div>

  <div class="b2">
    <%= f.label :キャプションを追加  %>
    <%= f.text_area :body, :size => "30x1" %>
  </div>

<div class="b3">
    <%#%= f.label :場所を追加  %>
    <%#%= f.text_field :place, :size => 30 %>
  </div>

<div class="b4">
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
  </div>
  <%= f.submit "投稿する",class:"btn-flat-vertical-border" %>
<% end %>

<div class="mapmap">



<input id="address" type="textbox" value="">
<input type="button" value="検索" onclick="codeAddress()">
<div id='map'></div>

<style>
#map {
  height: 500px;
  width: 500px;
}
</style>

<script>

let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}


let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        
        
        if (aft == true){
            marker.setMap(null);
        }

        
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	
        });

        
        aft = true

        
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        
        google.maps.event.addListener( marker, 'dragend', function(ev){
            
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLEMAP_API_KEY']%>&callback=initMap" async defer></script>

</div>
</div>
</div>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<header6>
  <div class="container">
    <blockquote>Posting Details
    <span>&mdash; nuit nuit
    </span>
    </blockquote>
  </div>
</header6>
<div class="b14">
<div class="tweet1">
  <div class="tweet2">
  <p><%= image_tag @tweet.image_url, size: "400px*600px" if @tweet.image?%></p>
  </div>
  <p><%= @tweet.body %></p>
  <p><%= @tweet.place %></p>
  <p><%= @tweet.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= button_to tweet_like_path(@tweet), method: :delete do %>
          <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= button_to tweet_likes_path(@tweet), method: :post do %>
          <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= @tweet.likes.count %>
    <% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.name unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_field :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
  <%= link_to "再投稿", edit_tweet_path(@tweet.id), class:"btn-vertical-border" %>
</div>

<div class="b30">
<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>

<div class="basyo">
<div id="display">投稿された場所</div>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 200px;
  text-aligen:center;
}
</style>

<script>
let map
let geocoder

const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: , lng:-73.9653},
    zoom:18,
  });

  marker = new google.maps.Marker({
    position:  {lat: , lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLEMAP_API_KEY']%>&callback=initMap" async defer></script>
</div>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'mymypage', :media => "all" %>
<header5>
  <div class="container">
    <blockquote>Mypage
    <span>&mdash; nuit nuit
    </span>
    </blockquote>
  </div>
</header5>
<div class="box0">

<div class="box1">
<div class="box2">
  <p> <%= @user.name %></p>
  </div>
<div class="box23">
<p><%= @user.profile %></p>
</div>
</div>

<div class="box3">
<p><%= image_tag @user.image_url, size: "250x250", class: "gazou" if @user.image? %></p>
</div>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path, class:"btn-flat-logo" %>
<% end %>]

<div class="box4">
<h2>あなたの投稿一覧</h2>
<% @user.tweets.each do |t| %>
<% end %>
</div>

<div class="box5">
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @tweets.each do |tweet|%>
        ( function() { 
          let markerLatLng = { lat: <%= tweet.lat %>, lng: <%= tweet.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= tweet_url(tweet.id) %>' target='_blank'><%= tweet.body %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLEMAP_API_KEY']%>&callback=initMap" async defer></script>
</div>